// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXFdOe1Dk0wRe51LHEo7aTTXw2vcRmUtw',
    appId: '1:201947652520:web:3e896366b2b6f144f4fd9d',
    messagingSenderId: '201947652520',
    projectId: 'classactivity13-9debc',
    authDomain: 'classactivity13-9debc.firebaseapp.com',
    storageBucket: 'classactivity13-9debc.firebasestorage.app',
    measurementId: 'G-CW33ZFP7GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARqO-Z32f55pE1fHCFtjwTfN__N_4r_mI',
    appId: '1:201947652520:android:483007dc38068b7cf4fd9d',
    messagingSenderId: '201947652520',
    projectId: 'classactivity13-9debc',
    storageBucket: 'classactivity13-9debc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwnarBMkQZ544ncGLbvyrGTLZlHTXN1uA',
    appId: '1:201947652520:ios:a89f0048f467c482f4fd9d',
    messagingSenderId: '201947652520',
    projectId: 'classactivity13-9debc',
    storageBucket: 'classactivity13-9debc.firebasestorage.app',
    iosBundleId: 'com.example.classActivity13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwnarBMkQZ544ncGLbvyrGTLZlHTXN1uA',
    appId: '1:201947652520:ios:a89f0048f467c482f4fd9d',
    messagingSenderId: '201947652520',
    projectId: 'classactivity13-9debc',
    storageBucket: 'classactivity13-9debc.firebasestorage.app',
    iosBundleId: 'com.example.classActivity13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXFdOe1Dk0wRe51LHEo7aTTXw2vcRmUtw',
    appId: '1:201947652520:web:c04fe32002a5b4b0f4fd9d',
    messagingSenderId: '201947652520',
    projectId: 'classactivity13-9debc',
    authDomain: 'classactivity13-9debc.firebaseapp.com',
    storageBucket: 'classactivity13-9debc.firebasestorage.app',
    measurementId: 'G-7GWX8QGSY3',
  );
}
